// src/webpack-angular-17/src/app/app.component.ts
import { AfterViewInit, Component, ElementRef, OnDestroy, ViewChild } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import * as alphaTab from '@coderline/alphatab';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent implements AfterViewInit, OnDestroy {
  #alphaTab!: alphaTab.AlphaTabApi;

  @ViewChild('alphaTab') alphaTabElement!: ElementRef<HTMLDivElement>

  playPause() {
    this.#alphaTab.playPause();
  }

  ngAfterViewInit(): void {
    this.#alphaTab = new alphaTab.AlphaTabApi(this.alphaTabElement.nativeElement, {
      core: {
        file: 'https://www.alphatab.net/files/canon.gp',
        fontDirectory: '/font/'
      },
      player: {
        enablePlayer: true,
        enableCursor: true,
        enableUserInteraction: true,
        soundFont: '/soundfont/sonivox.sf2'
      }
    } as alphaTab.Settings);
  }

  ngOnDestroy(): void {
    this.#alphaTab.destroy();
  }

  title = 'alphatab-app';
}

// src/vite-react/src/App.tsx
import { useEffect, useRef, useState } from 'react'
import './App.css'
import { AlphaTabApi, Settings } from '@coderline/alphatab'

function App() {
  const elementRef = useRef<HTMLDivElement>(null);
  const [api, setApi] = useState<AlphaTabApi>();

  useEffect(() => {
    const api = new AlphaTabApi(elementRef.current!, {
      core: {
        file: 'https://www.alphatab.net/files/canon.gp',
        fontDirectory: '/font/'
      },
      player: {
        enablePlayer: true,
        enableCursor: true,
        enableUserInteraction: true,
        soundFont: '/soundfont/sonivox.sf2'
      }
    } as Settings);
    
    setApi(api);

    return () => {
      console.log('destroy', elementRef, api);
      api.destroy();
    }
  }, []);

  function playPause() {
    api?.playPause();
  }

  return (
    <>
      Hello AlphaTab!

      <button onClick={() => playPause()}>Play/Pause</button>
      <div ref={elementRef}></div>
    </>
  )
}

export default App
